# Generated by Django 4.2.6 on 2023-10-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(verbose_name='Agrega el contenido de la publicacion'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='publishedDate',
            field=models.DateTimeField(verbose_name='Especificar fecha de publicacion'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='status',
            field=models.SmallIntegerField(verbose_name='Indica el estado de la publicacion'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Titulo de la publicacion'),
        ),
    ]
